name: ml-compare
channels:
    - defaults
dependencies:
    - python=3.7
    - jupyter
    - lightgbm=2.3
    - matplotlib-base=3.1.3
    - mkl
    - numpy=1.18.1
    - scikit-learn=0.22.1
    - scipy
    - pandas=1.0.1
    - pip=20.0.2
    - pip:
        - xgboost==1.1.1